#!/bin/bash

##
## Author : Zhangwei
## Contact: w-zhang16@mails.tsinghua.edu.cn
## Date   : 2019.06.11
##
## This program is designed to uninstall packages
##


conda uninstall fastqc samtools bedtools adapterremoval bowtie2 bismark picard numpy pysam


